export const USER_TOKEN_KEY = 'USER_TOKEN_KEY';
export const API_URL = 'https://dummy.restapiexample.com/api/v1/employees';
export const placeholder = {
  email: 'Email Address',
  password: 'Password',
  website: 'Search by website',
  ticketId: 'Search by Ticket Id',
  message: 'Comment here....',
  ticketTitle: 'Enter Ticket Title',
  ticketDescription: 'Enter Ticket Description',
  name:"Enter Name",
  phone:"Enter Phone No",
  companyName:"Enter Company Name",
  city:"Enter City",
  address:'Enter Address',
  country:"Enter Country",
  state:"Enter State",
  zipCode:"Enter Zip Code",
  oldPassword:"Enter Old Password",
  newPassword:"Enter New Password",
  confrimPassword:"Enter Confirm Password",
  uploadLogo:"click to upload",
  date:"select Date",
  websiteName:"Enter Website Name",
  websiteURL:"Enter Website URL",
  property:"Enter Property Id",
  userType:"Select User Type",
  name_edit:"Hillside Primary Care",
  street_address:"1923 Culebra Rd suite c",
  zip_code2:"78201",
  city2:"San Antonio",
  state2:"TX",
};

export const error = {
  email: 'Please Enter Valid Email',
  password: 'Please Enter Valid Passsword',
  newPassword: "New Password field is required",
  confrimPassword: "Confirm New Password field is required",
  passwordLength: "Password must be at least 6 digit",
  passWordNotMatch: "Password is not match"
};

export const titles = {
  title: 'Title',
  website: 'User Website',
  description: 'Description',
  emailAddress:"Email Address",
  name:"Name",
  phone:"Phone No.",
  password:"Password",
  userType:"User Type",
  email: 'Email',
  newPassword: 'New Password',
  confirmPassword: 'Confirm New Password',
  userType:"Select User Type",
  userDetail:"User Detail",
  editClient:"Edit Client",
  street:"Street Address",
  zipCode:"Zip Code",
  city:"City",
  state:"State",
  country:"Country",
  company:"Company Name",
  date:"Selected Date",
  services:"Service",
  url:"Website URL",
  property:"Property ID",
  addWebsite:"Add Website",
};
