//stacks
export const NAVIGATION_AUTH_LOADING_STACK = 'NAVIGATION_AUTH_LOADING_STACK';
export const NAVIGATION_AUTH_STACK = 'NAVIGATION_AUTH_STACK';
//screens
export const NAVIGATION_AUTH_LOADING_SCREEN = 'NAVIGATION_AUTH_LOADING_SCREEN';
export const RECORDING_SCREEN = 'RECORDING_SCREEN';
export const EMPLOYEE_SCREEN = 'EMPLOYEE_SCREEN';
export const MY_RECORD_SCREEN = 'MY_RECORD_SCREEN';
export const START_RECORDING_SCREEN = 'START_RECORDING_SCREEN';
export const SAVE_RECORDING = 'SAVE_RECORDING';
